# Generated by Django 6.0 on 2025-12-23 06:39

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='WebsitePolicy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('website', models.CharField(choices=[('NIVIT', 'NIVIT'), ('NIVMASS', 'NIVMASS'), ('NIVBRM', 'NIVBRM')], max_length=20)),
                ('policy_type', models.CharField(choices=[('TERMS', 'Terms of Services'), ('PRIVACY', 'Privacy Policy')], max_length=20)),
                ('title', models.CharField(max_length=255)),
                ('content', ckeditor.fields.RichTextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'unique_together': {('website', 'policy_type')},
            },
        ),
    ]
