# Generated by Django 6.0 on 2025-12-23 06:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nivservices', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='NIVBRMPrivacy',
            fields=[
            ],
            options={
                'verbose_name': 'Privacy Policy',
                'verbose_name_plural': 'Privacy Policy',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('nivservices.websitepolicy',),
        ),
        migrations.CreateModel(
            name='NIVBRMTerms',
            fields=[
            ],
            options={
                'verbose_name': 'Terms of Services',
                'verbose_name_plural': 'Terms of Services',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('nivservices.websitepolicy',),
        ),
        migrations.CreateModel(
            name='NIVITPrivacy',
            fields=[
            ],
            options={
                'verbose_name': 'Privacy Policy',
                'verbose_name_plural': 'Privacy Policy',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('nivservices.websitepolicy',),
        ),
        migrations.CreateModel(
            name='NIVITTerms',
            fields=[
            ],
            options={
                'verbose_name': 'Terms of Services',
                'verbose_name_plural': 'Terms of Services',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('nivservices.websitepolicy',),
        ),
        migrations.CreateModel(
            name='NIVMASSPrivacy',
            fields=[
            ],
            options={
                'verbose_name': 'Privacy Policy',
                'verbose_name_plural': 'Privacy Policy',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('nivservices.websitepolicy',),
        ),
        migrations.CreateModel(
            name='NIVMASSTerms',
            fields=[
            ],
            options={
                'verbose_name': 'Terms of Services',
                'verbose_name_plural': 'Terms of Services',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('nivservices.websitepolicy',),
        ),
        migrations.AlterModelOptions(
            name='websitepolicy',
            options={'verbose_name': 'Website Policy', 'verbose_name_plural': 'Website Policies'},
        ),
    ]
