# Generated by Django 6.0 on 2025-12-23 07:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nivservices', '0002_nivbrmprivacy_nivbrmterms_nivitprivacy_nivitterms_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='KnowledgeBase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('website', models.CharField(choices=[('NIVIT', 'NIVIT'), ('NIVMASS', 'NIVMASS'), ('NIVBRM', 'NIVBRM')], max_length=20)),
                ('title', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='KnowledgeBaseFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('pdf', models.FileField(upload_to='knowledgebase/')),
                ('knowledgebase', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files', to='nivservices.knowledgebase')),
            ],
        ),
        migrations.CreateModel(
            name='SOP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('website', models.CharField(choices=[('NIVIT', 'NIVIT'), ('NIVMASS', 'NIVMASS'), ('NIVBRM', 'NIVBRM')], max_length=20)),
                ('title', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='SOPFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('pdf', models.FileField(upload_to='sops/')),
                ('sop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files', to='nivservices.sop')),
            ],
        ),
        migrations.DeleteModel(
            name='NIVBRMPrivacy',
        ),
        migrations.DeleteModel(
            name='NIVBRMTerms',
        ),
        migrations.DeleteModel(
            name='NIVITPrivacy',
        ),
        migrations.DeleteModel(
            name='NIVITTerms',
        ),
        migrations.DeleteModel(
            name='NIVMASSPrivacy',
        ),
        migrations.DeleteModel(
            name='NIVMASSTerms',
        ),
        migrations.CreateModel(
            name='NIVBRMPolicy',
            fields=[
            ],
            options={
                'verbose_name': 'NIVBRM',
                'verbose_name_plural': 'NIVBRM',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('nivservices.websitepolicy',),
        ),
        migrations.CreateModel(
            name='NIVITPolicy',
            fields=[
            ],
            options={
                'verbose_name': 'NIVIT',
                'verbose_name_plural': 'NIVIT',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('nivservices.websitepolicy',),
        ),
        migrations.CreateModel(
            name='NIVMASSPolicy',
            fields=[
            ],
            options={
                'verbose_name': 'NIVMASS',
                'verbose_name_plural': 'NIVMASS',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('nivservices.websitepolicy',),
        ),
        migrations.AlterModelOptions(
            name='websitepolicy',
            options={},
        ),
        migrations.RemoveField(
            model_name='websitepolicy',
            name='created_at',
        ),
    ]
