# Generated by Django 6.0 on 2025-12-23 07:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nivservices', '0003_knowledgebase_knowledgebasefile_sop_sopfile_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='NIVBRMKnowledgeBase',
            fields=[
            ],
            options={
                'verbose_name': 'NIVBRM – Knowledge Base',
                'verbose_name_plural': 'NIVBRM – Knowledge Base',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('nivservices.knowledgebase',),
        ),
        migrations.CreateModel(
            name='NIVBRMSOP',
            fields=[
            ],
            options={
                'verbose_name': 'NIVBRM – SOPs',
                'verbose_name_plural': 'NIVBRM – SOPs',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('nivservices.sop',),
        ),
        migrations.CreateModel(
            name='NIVITKnowledgeBase',
            fields=[
            ],
            options={
                'verbose_name': 'NIVIT – Knowledge Base',
                'verbose_name_plural': 'NIVIT – Knowledge Base',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('nivservices.knowledgebase',),
        ),
        migrations.CreateModel(
            name='NIVITSOP',
            fields=[
            ],
            options={
                'verbose_name': 'NIVIT – SOPs',
                'verbose_name_plural': 'NIVIT – SOPs',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('nivservices.sop',),
        ),
        migrations.CreateModel(
            name='NIVMASSKnowledgeBase',
            fields=[
            ],
            options={
                'verbose_name': 'NIVMASS – Knowledge Base',
                'verbose_name_plural': 'NIVMASS – Knowledge Base',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('nivservices.knowledgebase',),
        ),
        migrations.CreateModel(
            name='NIVMASSSOP',
            fields=[
            ],
            options={
                'verbose_name': 'NIVMASS – SOPs',
                'verbose_name_plural': 'NIVMASS – SOPs',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('nivservices.sop',),
        ),
        migrations.AlterModelOptions(
            name='nivbrmpolicy',
            options={'verbose_name': 'NIVBRM – Policies', 'verbose_name_plural': 'NIVBRM – Policies'},
        ),
        migrations.AlterModelOptions(
            name='nivitpolicy',
            options={'verbose_name': 'NIVIT – Policies', 'verbose_name_plural': 'NIVIT – Policies'},
        ),
        migrations.AlterModelOptions(
            name='nivmasspolicy',
            options={'verbose_name': 'NIVMASS – Policies', 'verbose_name_plural': 'NIVMASS – Policies'},
        ),
        migrations.RemoveField(
            model_name='knowledgebase',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='sop',
            name='created_at',
        ),
    ]
