# Generated by Django 6.0 on 2025-12-23 07:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nivservices', '0004_nivbrmknowledgebase_nivbrmsop_nivitknowledgebase_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='NIVBRMPolicy',
        ),
        migrations.DeleteModel(
            name='NIVITPolicy',
        ),
        migrations.DeleteModel(
            name='NIVMASSPolicy',
        ),
        migrations.CreateModel(
            name='NIVBRMPrivacy',
            fields=[
            ],
            options={
                'verbose_name': 'NIVBRM – Privacy Policy',
                'verbose_name_plural': 'NIVBRM – Privacy Policy',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('nivservices.websitepolicy',),
        ),
        migrations.CreateModel(
            name='NIVBRMTerms',
            fields=[
            ],
            options={
                'verbose_name': 'NIVBRM – Terms of Services',
                'verbose_name_plural': 'NIVBRM – Terms of Services',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('nivservices.websitepolicy',),
        ),
        migrations.CreateModel(
            name='NIVITPrivacy',
            fields=[
            ],
            options={
                'verbose_name': 'NIVIT – Privacy Policy',
                'verbose_name_plural': 'NIVIT – Privacy Policy',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('nivservices.websitepolicy',),
        ),
        migrations.CreateModel(
            name='NIVITTerms',
            fields=[
            ],
            options={
                'verbose_name': 'NIVIT – Terms of Services',
                'verbose_name_plural': 'NIVIT – Terms of Services',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('nivservices.websitepolicy',),
        ),
        migrations.CreateModel(
            name='NIVMASSPrivacy',
            fields=[
            ],
            options={
                'verbose_name': 'NIVMASS – Privacy Policy',
                'verbose_name_plural': 'NIVMASS – Privacy Policy',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('nivservices.websitepolicy',),
        ),
        migrations.CreateModel(
            name='NIVMASSTerms',
            fields=[
            ],
            options={
                'verbose_name': 'NIVMASS – Terms of Services',
                'verbose_name_plural': 'NIVMASS – Terms of Services',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('nivservices.websitepolicy',),
        ),
    ]
