# Generated by Django 6.0 on 2025-12-23 07:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nivservices', '0005_delete_nivbrmpolicy_delete_nivitpolicy_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='knowledgebase',
            name='title',
        ),
        migrations.RemoveField(
            model_name='sop',
            name='title',
        ),
    ]
