# Generated by Django 6.0 on 2026-01-12 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nivservices', '0006_remove_knowledgebase_title_remove_sop_title'),
    ]

    operations = [
        migrations.CreateModel(
            name='NIVPAPKnowledgeBase',
            fields=[
            ],
            options={
                'verbose_name': 'NIVPAP – Knowledge Base',
                'verbose_name_plural': 'NIVPAP – Knowledge Base',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('nivservices.knowledgebase',),
        ),
        migrations.CreateModel(
            name='NIVPAPPrivacy',
            fields=[
            ],
            options={
                'verbose_name': 'NIVPAP – Privacy Policy',
                'verbose_name_plural': 'NIVPAP – Privacy Policy',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('nivservices.websitepolicy',),
        ),
        migrations.CreateModel(
            name='NIVPAPReturnRefund',
            fields=[
            ],
            options={
                'verbose_name': 'NIVPAP – Return & Refund Policy',
                'verbose_name_plural': 'NIVPAP – Return & Refund Policy',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('nivservices.websitepolicy',),
        ),
        migrations.CreateModel(
            name='NIVPAPShipment',
            fields=[
            ],
            options={
                'verbose_name': 'NIVPAP – Shipment Policy',
                'verbose_name_plural': 'NIVPAP – Shipment Policy',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('nivservices.websitepolicy',),
        ),
        migrations.CreateModel(
            name='NIVPAPSOP',
            fields=[
            ],
            options={
                'verbose_name': 'NIVPAP – SOPs',
                'verbose_name_plural': 'NIVPAP – SOPs',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('nivservices.sop',),
        ),
        migrations.CreateModel(
            name='NIVPAPTerms',
            fields=[
            ],
            options={
                'verbose_name': 'NIVPAP – Terms of Services',
                'verbose_name_plural': 'NIVPAP – Terms of Services',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('nivservices.websitepolicy',),
        ),
        migrations.AlterField(
            model_name='knowledgebase',
            name='website',
            field=models.CharField(choices=[('NIVIT', 'NIVIT'), ('NIVMASS', 'NIVMASS'), ('NIVBRM', 'NIVBRM'), ('NIVPAP', 'NIVPAP')], max_length=20),
        ),
        migrations.AlterField(
            model_name='sop',
            name='website',
            field=models.CharField(choices=[('NIVIT', 'NIVIT'), ('NIVMASS', 'NIVMASS'), ('NIVBRM', 'NIVBRM'), ('NIVPAP', 'NIVPAP')], max_length=20),
        ),
        migrations.AlterField(
            model_name='websitepolicy',
            name='policy_type',
            field=models.CharField(choices=[('TERMS', 'Terms of Services'), ('PRIVACY', 'Privacy Policy'), ('RETURN_REFUND', 'Return & Refund Policy'), ('SHIPMENT', 'Shipment Policy')], max_length=30),
        ),
        migrations.AlterField(
            model_name='websitepolicy',
            name='website',
            field=models.CharField(choices=[('NIVIT', 'NIVIT'), ('NIVMASS', 'NIVMASS'), ('NIVBRM', 'NIVBRM'), ('NIVPAP', 'NIVPAP')], max_length=20),
        ),
    ]
