# Generated by Django 6.0 on 2026-01-12 08:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nivservices', '0007_nivpapknowledgebase_nivpapprivacy_nivpapreturnrefund_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='NIVBRMKnowledgeBase',
        ),
        migrations.DeleteModel(
            name='NIVBRMSOP',
        ),
        migrations.DeleteModel(
            name='NIVITKnowledgeBase',
        ),
        migrations.DeleteModel(
            name='NIVITSOP',
        ),
        migrations.DeleteModel(
            name='NIVMASSKnowledgeBase',
        ),
        migrations.DeleteModel(
            name='NIVMASSSOP',
        ),
        migrations.DeleteModel(
            name='NIVPAPKnowledgeBase',
        ),
        migrations.DeleteModel(
            name='NIVPAPSOP',
        ),
        migrations.AlterModelOptions(
            name='knowledgebase',
            options={'verbose_name': 'Knowledge Base', 'verbose_name_plural': 'Knowledge Bases'},
        ),
        migrations.AlterModelOptions(
            name='sop',
            options={'verbose_name': 'SOP', 'verbose_name_plural': 'SOPs'},
        ),
    ]
