# Generated by Django 6.0 on 2026-01-12 08:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nivservices', '0008_delete_nivbrmknowledgebase_delete_nivbrmsop_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='knowledgebasefile',
            options={'verbose_name': 'Knowledge Base File', 'verbose_name_plural': 'Knowledge Base Files'},
        ),
        migrations.AlterModelOptions(
            name='sopfile',
            options={'verbose_name': 'SOP File', 'verbose_name_plural': 'SOP Files'},
        ),
        migrations.AlterModelOptions(
            name='websitepolicy',
            options={'verbose_name': 'Website Policy', 'verbose_name_plural': 'Website Policies'},
        ),
    ]
